

FROM quay.io/BLACK-PANTHER-MD
RUN git clone https://github.com/ibrahimaitech/BLACK-PANTHER-MD.git //root/ibrahimaitech
WORKDIR //root/ibrahimaitech/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
